/**
 * Insight Summarizer Agent
 * =========================
 *
 * Stage 6 — Report
 *
 * Takes the raw findings from prior stages (anomalies, forecasts, causal
 * relationships, statistical profiles) and synthesizes them into a concise
 * set of human-readable insights, ranked by business impact.
 *
 * This is the first of three report-stage agents that use the LLM Gateway
 * to call an LLM. By routing through the gateway rather than calling
 * `z-ai-web-dev-sdk` directly, every LLM call is automatically:
 *   - captured as a trajectory step (tokens, cost, latency, prompt, response)
 *   - scrubbed of PII in the response
 *   - routed with multi-provider fallback
 *
 * The AReaL paper's central insight: trajectory capture belongs at the
 * HTTP boundary (the LLM gateway proxy), not via agent opt-in. Wrap an
 * agent's LLM access in the gateway and it gets trajectory capture for
 * free.
 */

import { z } from 'zod';
import { AgentStage, AgentTier, AgentStability } from '@busara/core';
import {
  BaseAgent,
  EnhancedAgentMetadata,
  EnhancedAgentContext,
  AgentResult,
  createAgentMetadata,
} from '../../core';
import { LLMGateway, type ChatMessage } from '../../llm-gateway';
import { chatWithGatewayFallback } from './llmFallback';

// ============================================================================
// Agent Metadata
// ============================================================================

const metadata = createAgentMetadata({
  id: 'insight_summarizer',
  name: 'Insight Summarizer',
  description:
    'Synthesizes raw analytical findings into a concise set of business-actionable insights, ranked by impact and confidence. Routes its LLM call through the LLM Gateway so the call is automatically captured in the trajectory.',
  version: '1.0.0',

  stage: 'report' as AgentStage,
  stageNumber: 6,
  tier: 'core' as AgentTier,
  stability: 'beta' as AgentStability,

  author: 'Busara Team',
  license: 'MIT',

  dependencies: ['analysis_strategist', 'anomaly_sentinel', 'forecasting_oracle', 'causal_architect'],

  timeoutMs: 45000,
  maxRetries: 2,

  capabilities: ['insight_synthesis', 'narrative_generation', 'impact_ranking', 'llm_powered'],
  category: 'reporting',
  tags: ['insights', 'summary', 'llm', 'report'],

  inputDescription: 'Prior-stage analytical findings (anomalies, forecasts, causal links)',
  outputDescription: 'Ranked list of insights with titles, descriptions, and confidence scores',
  inputSchema: {
    schema: z.object({
      findings: z.array(z.object({
        title: z.string(),
        description: z.string(),
        confidence: z.number(),
      })).default([]),
      datasetSummary: z.object({
        rowCount: z.number(),
        columnCount: z.number(),
      }).optional(),
    }),
    description: 'Analytical findings from prior stages',
  },
  outputSchema: {
    schema: z.object({
      insights: z.array(z.object({
        title: z.string(),
        description: z.string(),
        confidence: z.number(),
        impact: z.enum(['high', 'medium', 'low']),
        category: z.string(),
      })),
      summary: z.string(),
      model: z.string(),
      provider: z.string(),
    }),
    description: 'Ranked insights generated by the LLM',
  },
  configSchema: {
    schema: z.object({
      maxInsights: z.number().int().positive().max(20).default(7),
      complexity: z.enum(['low', 'medium', 'high']).default('medium'),
    }),
    defaults: { maxInsights: 7, complexity: 'medium' },
    description: 'Insight summarizer configuration',
  },

  memoryLimitMB: 256,
  cpuLimit: 1,
  gpuRequired: false,

  icon: 'Lightbulb',
  color: '#f59e0b',
});

// ============================================================================
// Agent Implementation
// ============================================================================

export class InsightSummarizerAgent extends BaseAgent {
  readonly metadata: EnhancedAgentMetadata = metadata;

  async execute(context: EnhancedAgentContext): Promise<AgentResult> {
    const start = Date.now();

    try {
      // Gather findings from prior-stage agents.
      const previousResults = context.previousResults ?? new Map();
      const findings = this.collectFindings(previousResults, context.dataframe);

      if (findings.length === 0) {
        return this.createResult(
          { insights: [], summary: 'No findings to summarize.', model: 'none', provider: 'none' },
          { findingsCount: 0 },
          Date.now() - start,
        );
      }

      const maxInsights = (context.config?.maxInsights as number) ?? 7;
      const complexity = (context.config?.complexity as 'low' | 'medium' | 'high') ?? 'medium';

      // Build the prompt.
      const systemPrompt = `You are Busara, an elite data analyst AI. Synthesize analytical findings into concise, business-actionable insights. Each insight must:
1. Lead with the most important number.
2. Be specific and quantitative.
3. Be actionable — answer "so what should we DO?".
4. Be honest about uncertainty.

Return ${maxInsights} insights max, ranked by business impact (revenue > risk > efficiency > curiosity). Format each as:
- **[TITLE]** | confidence: X% | impact: high|medium|low | category: anomalies|forecast|causal|quality
  Description (1-2 sentences).`;

      const userPrompt = this.buildUserPrompt(findings, context.dataframe);

      // Route through the LLM Gateway — trajectory capture is automatic.
      // If the gateway exhausts every provider, fall back to a direct GLM
      // SDK call so the agent still produces a result.
      const gateway = new LLMGateway({ recorder: context.trajectoryRecorder });
      const messages: ChatMessage[] = [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ];
      const response = await chatWithGatewayFallback(
        gateway,
        messages,
        { complexity, maxTokens: 1500, temperature: 0.3 },
        { maxTokens: 1500, temperature: 0.3 },
      );

      const insights = this.parseInsights(response.text, maxInsights);

      return this.createResult(
        {
          insights,
          summary: response.text,
          model: response.model,
          provider: response.provider,
        },
        {
          findingsCount: findings.length,
          insightsCount: insights.length,
          tokensIn: response.tokensIn,
          tokensOut: response.tokensOut,
          cost: response.cost,
          latencyMs: response.latencyMs,
          fallbacksTried: response.fallbacksTried.length,
        },
        Date.now() - start,
      );
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      return this.createError(errorMessage, Date.now() - start);
    }
  }

  /** Pull findings from prior-stage agent results. */
  private collectFindings(
    previousResults: Map<string, AgentResult>,
    dataframe: Record<string, unknown>[],
  ): Array<{ title: string; description: string; confidence: number }> {
    const findings: Array<{ title: string; description: string; confidence: number }> = [];

    // From anomaly sentinel
    const anomalyResult = previousResults.get('anomaly_sentinel')?.output as any;
    if (anomalyResult?.anomalies?.length > 0) {
      findings.push({
        title: `${anomalyResult.anomalies.length} Anomalies Detected`,
        description: `Found ${anomalyResult.anomalies.length} anomalous data points.`,
        confidence: 0.88,
      });
    }

    // From forecasting oracle
    const forecastResult = previousResults.get('forecasting_oracle')?.output as any;
    if (forecastResult?.forecast?.length > 0) {
      findings.push({
        title: `Forecast Trend: ${forecastResult.trend ?? 'unknown'}`,
        description: `Forecast accuracy: ${forecastResult.accuracy ?? 'N/A'}% using ${forecastResult.method ?? 'N/A'}.`,
        confidence: (forecastResult.accuracy ?? 50) / 100,
      });
    }

    // From causal architect
    const causalResult = previousResults.get('causal_architect')?.output as any;
    if (causalResult?.relationships?.length > 0) {
      const top = causalResult.relationships[0];
      findings.push({
        title: `${top.cause} → ${top.effect}`,
        description: `Strength: ${top.strength}, correlation: ${top.correlation}.`,
        confidence: top.confidence ?? 0.7,
      });
    }

    // From data overview
    if (dataframe?.length > 0) {
      findings.push({
        title: 'Dataset Overview',
        description: `Analyzed ${dataframe.length} rows across ${Object.keys(dataframe[0]).length} columns.`,
        confidence: 0.98,
      });
    }

    return findings;
  }

  private buildUserPrompt(
    findings: Array<{ title: string; description: string; confidence: number }>,
    dataframe: Record<string, unknown>[],
  ): string {
    const lines = findings.map(f => `- ${f.title}: ${f.description} (confidence: ${(f.confidence * 100).toFixed(0)}%)`);
    return `Synthesize the following ${findings.length} analytical findings from a ${dataframe?.length ?? 0}-row dataset into ${this.metadata.configSchema.defaults.maxInsights ?? 7} ranked insights.

## Findings
${lines.join('\n')}

Generate the insights now:`;
  }

  /** Parse the LLM's bullet-point response into structured insights. */
  private parseInsights(text: string, maxInsights: number): Array<{
    title: string; description: string; confidence: number; impact: 'high' | 'medium' | 'low'; category: string;
  }> {
    if (!text) return [];
    const insights: Array<{
      title: string; description: string; confidence: number; impact: 'high' | 'medium' | 'low'; category: string;
    }> = [];

    const lines = text.split('\n').map(l => l.trim()).filter(l => l.startsWith('-'));
    for (const line of lines) {
      // Match: - **[TITLE]** | confidence: X% | impact: high | category: anomalies
      const m = line.match(/^-\s*\*{0,2}\[?(.+?)\]?\*{0,2}\s*\|\s*confidence:\s*(\d+)%?\s*\|\s*impact:\s*(high|medium|low)\s*\|\s*category:\s*(\w+)/i);
      if (m) {
        insights.push({
          title: m[1].trim(),
          description: '', // The description follows on the next line in practice
          confidence: Number(m[2]) / 100,
          impact: m[3].toLowerCase() as 'high' | 'medium' | 'low',
          category: m[4].toLowerCase(),
        });
      }
      if (insights.length >= maxInsights) break;
    }

    return insights;
  }
}
