/**
 * Natural Language Query Agent
 * =============================
 *
 * Stage 6 — Report
 *
 * Translates a natural-language question about the dataset into a
 * structured analysis intent + entities + suggested visualization + a
 * short narrative answer generated by an LLM.
 *
 * Routes its LLM call through the LLM Gateway (not z-ai-web-dev-sdk
 * directly) so the call is automatically captured in the trajectory with
 * token usage, cost, latency, and PII scrubbing. This is the AReaL
 * paper's "HTTP boundary" instrumentation pattern: zero-code capture.
 */

import { z } from 'zod';
import { AgentStage, AgentTier, AgentStability } from '@busara/core';
import {
  BaseAgent,
  EnhancedAgentMetadata,
  EnhancedAgentContext,
  AgentResult,
  createAgentMetadata,
} from '../../core';
import { LLMGateway, type ChatMessage } from '../../llm-gateway';
import { chatWithGatewayFallback } from './llmFallback';

// ============================================================================
// Agent Metadata
// ============================================================================

const metadata = createAgentMetadata({
  id: 'natural_language_query',
  name: 'Natural Language Query',
  description:
    'Interprets a natural-language question about the dataset and produces a structured analysis intent, suggested visualization, SQL equivalent, and a short narrative answer. Routes its LLM call through the LLM Gateway for automatic trajectory capture.',
  version: '1.0.0',

  stage: 'report' as AgentStage,
  stageNumber: 6,
  tier: 'core' as AgentTier,
  stability: 'beta' as AgentStability,

  author: 'Busara Team',
  license: 'MIT',

  dependencies: ['data_ingestion', 'schema_inference'],

  timeoutMs: 30000,
  maxRetries: 2,

  capabilities: ['nlq_interpretation', 'intent_detection', 'sql_generation', 'llm_powered'],
  category: 'reporting',
  tags: ['nlq', 'natural_language', 'query', 'llm', 'report'],

  inputDescription: 'A natural-language query plus the dataset schema',
  outputDescription: 'Structured interpretation: intent, entities, visualization, SQL, narrative answer',
  inputSchema: {
    schema: z.object({
      query: z.string().min(1),
      columns: z.array(z.string()).default([]),
    }),
    description: 'NLQ query + dataset columns',
  },
  outputSchema: {
    schema: z.object({
      intent: z.string(),
      entities: z.array(z.object({
        type: z.string(),
        value: z.string(),
        confidence: z.number(),
      })),
      suggestedVisualization: z.string(),
      sqlEquivalent: z.string(),
      answer: z.string(),
      model: z.string(),
      provider: z.string(),
    }),
    description: 'Structured NLQ interpretation + narrative answer',
  },
  configSchema: {
    schema: z.object({
      complexity: z.enum(['low', 'medium', 'high']).default('medium'),
    }),
    defaults: { complexity: 'medium' },
    description: 'NLQ agent configuration',
  },

  memoryLimitMB: 256,
  cpuLimit: 1,
  gpuRequired: false,

  icon: 'MessageSquare',
  color: '#06b6d4',
});

// ============================================================================
// Agent Implementation
// ============================================================================

export class NaturalLanguageQueryAgent extends BaseAgent {
  readonly metadata: EnhancedAgentMetadata = metadata;

  async execute(context: EnhancedAgentContext): Promise<AgentResult> {
    const start = Date.now();

    try {
      // The natural-language query comes in via config.nlqQuery (per the
      // existing AnalysisConfig convention).
      const query = (context.config?.nlqQuery as string) ?? '';
      if (!query || !query.trim()) {
        return this.createSkipped('no_nlq_query');
      }

      const columns = context.dataframe?.[0] ? Object.keys(context.dataframe[0]) : [];
      const complexity = (context.config?.complexity as 'low' | 'medium' | 'high') ?? 'medium';

      // Quick rule-based intent detection (used as a hint to the LLM).
      const heuristicIntent = this.detectIntent(query.toLowerCase());

      const systemPrompt = `You are Busara's NLQ interpreter. Given a natural-language question about a dataset, produce:
1. intent — one of: time_series_forecast, correlation_analysis, causal_analysis, anomaly_detection, clustering, comparison, distribution_analysis, descriptive_summary, aggregation, count, ranking
2. entities — column names and values mentioned in the question
3. suggestedVisualization — best chart type for the intent
4. sqlEquivalent — a SQL query that would answer the question
5. answer — a 1-2 sentence direct answer using only what's inferable from the question + schema

Format your response as:
INTENT: <intent>
VISUALIZATION: <chart_type>
SQL: <sql>
ENTITIES: <comma-separated>
ANSWER: <answer>`;

      const userPrompt = `Question: "${query}"

Available columns: ${columns.join(', ') || '(unknown — schema not provided)'}
Heuristic intent: ${heuristicIntent}

Interpret the question:`;

      // Route through the LLM Gateway — trajectory capture is automatic.
      // If the gateway exhausts every provider, fall back to a direct GLM
      // SDK call so the agent still produces a result.
      const gateway = new LLMGateway({ recorder: context.trajectoryRecorder });
      const messages: ChatMessage[] = [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ];
      const response = await chatWithGatewayFallback(
        gateway,
        messages,
        { complexity, maxTokens: 600, temperature: 0.2 },
        { maxTokens: 600, temperature: 0.2 },
      );

      const parsed = this.parseResponse(response.text, query, columns, heuristicIntent);

      return this.createResult(
        {
          intent: parsed.intent,
          entities: parsed.entities,
          suggestedVisualization: parsed.suggestedVisualization,
          sqlEquivalent: parsed.sqlEquivalent,
          answer: parsed.answer,
          model: response.model,
          provider: response.provider,
        },
        {
          tokensIn: response.tokensIn,
          tokensOut: response.tokensOut,
          cost: response.cost,
          latencyMs: response.latencyMs,
          fallbacksTried: response.fallbacksTried.length,
        },
        Date.now() - start,
      );
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      return this.createError(errorMessage, Date.now() - start);
    }
  }

  /** Lightweight rule-based intent detection (used as a hint to the LLM). */
  private detectIntent(q: string): string {
    if (/trend|over time|forecast|predict|future/.test(q)) return 'time_series_forecast';
    if (/correlat|relat|connect|affect|impact|influence/.test(q)) return 'correlation_analysis';
    if (/caus|because of|due to|leads to|drives/.test(q)) return 'causal_analysis';
    if (/anomal|outlier|unusual|abnormal|weird/.test(q)) return 'anomaly_detection';
    if (/cluster|segment|group|categor/.test(q)) return 'clustering';
    if (/compare|versus|vs|difference/.test(q)) return 'comparison';
    if (/distribut|spread|histogram/.test(q)) return 'distribution_analysis';
    if (/average|mean|median|total|sum/.test(q)) return 'aggregation';
    if (/count|how many|frequency/.test(q)) return 'count';
    if (/top|bottom|best|worst|highest|lowest|rank/.test(q)) return 'ranking';
    return 'descriptive_summary';
  }

  /** Parse the LLM's structured response. */
  private parseResponse(
    text: string,
    query: string,
    columns: string[],
    heuristicIntent: string,
  ): {
    intent: string;
    entities: Array<{ type: string; value: string; confidence: number }>;
    suggestedVisualization: string;
    sqlEquivalent: string;
    answer: string;
  } {
    const get = (key: string): string => {
      const m = text.match(new RegExp(`${key}:\\s*(.+?)(?:\\n\\s*[A-Z]+:|$)`, 'is'));
      return m ? m[1].trim() : '';
    };

    const intent = get('INTENT') || heuristicIntent;
    const suggestedVisualization = get('VISUALIZATION') || this.vizForIntent(intent);
    const sqlEquivalent = get('SQL') || `SELECT * FROM data LIMIT 100;`;
    const entitiesStr = get('ENTITIES') || '';
    const answer = get('ANSWER') || '';

    // Entities: combine LLM-suggested entities with column-name matches.
    const entities: Array<{ type: string; value: string; confidence: number }> = [];
    for (const col of columns) {
      if (query.toLowerCase().includes(col.toLowerCase())) {
        entities.push({ type: 'column', value: col, confidence: 0.95 });
      }
    }
    for (const part of entitiesStr.split(',').map(s => s.trim()).filter(Boolean)) {
      if (!entities.some(e => e.value === part)) {
        entities.push({ type: 'unknown', value: part, confidence: 0.5 });
      }
    }

    return { intent, entities, suggestedVisualization, sqlEquivalent, answer };
  }

  private vizForIntent(intent: string): string {
    const map: Record<string, string> = {
      time_series_forecast: 'line',
      correlation_analysis: 'scatter',
      causal_analysis: 'scatter',
      anomaly_detection: 'scatter',
      clustering: 'scatter',
      comparison: 'bar',
      distribution_analysis: 'histogram',
      aggregation: 'bar',
      count: 'bar',
      ranking: 'bar',
      descriptive_summary: 'table',
    };
    return map[intent] || 'table';
  }
}
